[theme]
base = "dark"
primaryColor = "#FF6600"
backgroundColor = "#121619"
secondaryBackgroundColor = "#1E2226"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
