[theme]
primaryColor = "#E35302"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#252525"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
