[auth]
client_id = "dummy-client-id"
client_secret = "dummy-client-secret"
tenant_id = "dummy-tenant-id"
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "dummy-cookie-secret-at-least-32-chars-long"
server_metadata_url = "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"
expose_tokens = ["id", "access"]

[auth.group_mappings]
"dummy-admin-group-oid" = "admin"
"dummy-analyst-group-oid" = "analyst"
"dummy-viewer-group-oid" = "viewer"
